language: node_js
node_js:
  - "iojs"
  - "7"

install: cd gui && npm install && bower install && cd ../container && npm install
script: cd ../gui && grunt jshint && grunt && cd ../container && grunt jshint 
